/**
 * src/config/seo/manifest.ts
 * Central SEO Manifest — Authoritative single source of truth for URL architecture,
 * lifecycle state, indexability, canonical relationships, and migration provenance.
 */

import type { SeoManifestRecord } from './types';
import { GONE_PATHS_RAW } from './gone';
import { RAW_REDIRECT_RULES } from './redirects';
import { PLANNED_PAGES } from '../planned-pages';
import { normalizePath } from '../../lib/seo/normalize';

/**
 * 1. Owner-Approved Core Public Pages (INDEX with READY Content)
 */
export const APPROVED_INDEX_PAGES: SeoManifestRecord[] = [
  {
    path: '/',
    state: 'INDEX',
    pageType: 'hub',
    contentCluster: 'general',
    primaryIntent: 'buyback',
    canonical: 'self',
    title: 'รับซื้อสินค้าไอทีมือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อสินค้าไอทีมือสอง โน๊ตบุ๊ค คอม MacBook iPhone iPad กล้อง ลำโพง และอุปกรณ์ไอที ส่งรุ่น รูป สภาพและอุปกรณ์เพื่อเช็กราคาเบื้องต้นก่อนตัดสินใจขาย',
    h1: 'รับซื้อสินค้าไอทีมือสอง เช็กราคาก่อนขายก่อนตัดสินใจ',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อลำโพง-อุดรธานี/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'audio',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อลำโพง/',
    title: 'รับซื้อลำโพง อุดรธานี Marshall JBL ลำโพงบลูทูธมือสอง | เรารับซื้อ.com',
    description: 'บริการรับซื้อลำโพงมือสองในจังหวัดอุดรธานี Marshall, JBL, Harman Kardon เช็กราคา ตรวจสอบสภาพ นัดรับได้สะดวก',
    h1: 'รับซื้อลำโพงมือสอง อุดรธานี ประเมินราคาก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'Approved historical survivor rewritten page for Udon Thani speaker market.'
  },
  {
    path: '/รับซื้อลำโพง-สารคาม/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'audio',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อลำโพง/',
    title: 'รับซื้อลำโพง มหาสารคาม Marshall JBL ลำโพงบลูทูธมือสอง | เรารับซื้อ.com',
    description: 'บริการรับซื้อลำโพงมือสองในจังหวัดมหาสารคาม Marshall, JBL เช็กราคาเบื้องต้นก่อนขาย นัดรับในพื้นที่ สะดวก ปลอดภัย',
    h1: 'รับซื้อลำโพงมือสอง มหาสารคาม',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'Approved historical survivor preserved slug for Mahasarakham speaker market.'
  },
  {
    path: '/รับซื้อ/',
    state: 'INDEX',
    pageType: 'hub',
    contentCluster: 'general',
    primaryIntent: 'buyback',
    canonical: 'self',
    title: 'รับซื้อสินค้าไอทีมือสอง มีอะไรบ้าง | เรารับซื้อ.com',
    description: 'รวมสินค้าที่รับซื้อ โน๊ตบุ๊ค คอม MacBook iPhone iPad กล้อง ลำโพง ซากคอม และ Server เลือกหมวดสินค้า ดูข้อมูลที่ต้องใช้ และเช็กราคาก่อนขาย',
    h1: 'รับซื้อสินค้าไอทีมือสอง เลือกประเภทสินค้าที่ต้องการขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'notebook',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อโน๊ตบุ๊คมือสอง Gaming Notebook เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสอง Notebook Laptop และ Gaming Notebook เช็กราคาจากรุ่น CPU RAM SSD การ์ดจอ แบตเตอรี่ สภาพและอุปกรณ์ ส่งข้อมูลประเมินก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คมือสอง เช็กรุ่น สเปก และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อคอม/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'pc',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อคอมมือสอง Gaming PC และคอมประกอบ เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อคอมพิวเตอร์มือสอง Gaming PC และคอมประกอบ ประเมินจาก CPU การ์ดจอ RAM SSD เมนบอร์ด PSU และสภาพเครื่อง ส่งสเปกและรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อคอมมือสอง Gaming PC เช็กสเปกและราคาก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อแมคบุ๊ค/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'macbook',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อ MacBook มือสอง MacBook Air Pro เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ MacBook มือสอง MacBook Air และ MacBook Pro ประเมินจากรุ่น ชิป M1 M2 M3 M4 RAM SSD แบตเตอรี่ สภาพจอและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อ MacBook มือสอง เช็กรุ่น ชิป แบตเตอรี่และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อไอโฟน/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'iphone',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อ iPhone มือสอง เช็กรุ่น แบตเตอรี่และสภาพก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ iPhone มือสองหลายรุ่น ประเมินจากรุ่น ความจุ สุขภาพแบตเตอรี่ หน้าจอ Face ID กล้อง สภาพเครื่อง ประวัติซ่อมและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อ iPhone มือสอง เช็กรุ่น ความจุ แบตเตอรี่และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อไอแพด/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'ipad',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อ iPad มือสอง เช็กรุ่น ความจุ แบตเตอรี่และสภาพ | เรารับซื้อ.com',
    description: 'รับซื้อ iPad มือสอง iPad Air Pro mini ประเมินจากรุ่น ความจุ Wi-Fi หรือ Cellular หน้าจอ แบตเตอรี่ สภาพ ประวัติซ่อมและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อ iPad มือสอง เช็กรุ่น ความจุ และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อกล้อง/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'camera',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อกล้องมือสอง กล้อง Mirrorless DSLR และเลนส์ | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสอง Mirrorless DSLR และเลนส์ ประเมินจากรุ่น Body เลนส์ สภาพ Sensor Shutter หน้าจอ แบตเตอรี่ เชื้อรา ฝ้า และอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อกล้องมือสอง เช็กรุ่น Body เลนส์ และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อลำโพง/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'audio',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อลำโพงมือสอง Bluetooth JBL Marshall เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อลำโพงมือสอง Bluetooth และลำโพงพกพา ประเมินจากรุ่น แบตเตอรี่ เสียง ดอกลำโพง การเชื่อมต่อ สภาพ อุปกรณ์และประวัติซ่อม ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อลำโพงมือสอง เช็กรุ่น เสียง แบตเตอรี่และสภาพก่อนขาย',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อซากคอมพิวเตอร์/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'pc',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อคอม/',
    title: 'รับซื้อซากคอมพิวเตอร์ คอมเสีย เปิดไม่ติด และอะไหล่ | เรารับซื้อ.com',
    description: 'รับซื้อซากคอมพิวเตอร์ คอมเสีย เปิดไม่ติด และชิ้นส่วนคอม ประเมินจาก CPU การ์ดจอ RAM SSD เมนบอร์ด PSU อาการและสภาพ ส่งสเปกกับรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อซากคอมพิวเตอร์ คอมเสีย เปิดไม่ติด เช็กมูลค่าชิ้นส่วนก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อ-server/',
    state: 'INDEX',
    pageType: 'category',
    contentCluster: 'b2b',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อ Server มือสอง เซิร์ฟเวอร์องค์กร เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ Server มือสองและเซิร์ฟเวอร์องค์กร ประเมินจากรุ่น CPU RAM ECC Storage RAID Controller Network PSU สภาพและอุปกรณ์ ส่งสเปกกับรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อ Server มือสอง เช็กสเปก อุปกรณ์ และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'READY'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊คอุบล-notebook-laptop-จ/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คอุบลราชธานี Notebook Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในอุบลราชธานี Notebook Laptop และ Gaming Notebook ส่งรุ่น สเปก รูป แบตเตอรี่ สภาพและอุปกรณ์เพื่อเช็กราคาเบื้องต้นก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คอุบลราชธานี เช็กรุ่น สเปก และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 1 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อคอม-อุดรธานี/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'pc',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อคอม/',
    title: 'รับซื้อคอมอุดรธานี Gaming PC คอมประกอบ เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อคอมมือสองในอุดรธานี Desktop Gaming PC และคอมประกอบ ประเมินจาก CPU การ์ดจอ RAM SSD เมนบอร์ด PSU สภาพและอุปกรณ์ ส่งสเปกกับรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อคอมอุดรธานี เช็กสเปก Gaming PC และคอมประกอบก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 1 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อคอม-ขอนแก่น/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'pc',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อคอม/',
    title: 'รับซื้อคอมขอนแก่น Gaming PC คอมประกอบ เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อคอมมือสองในขอนแก่น Desktop Gaming PC Workstation และคอมประกอบ ประเมินจาก CPU GPU RAM SSD เมนบอร์ด PSU สภาพและอุปกรณ์ ส่งสเปกกับรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อคอมขอนแก่น เช็กสเปกและมูลค่า Hardware ก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 1 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-บุรีรัม/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คบุรีรัมย์ Notebook Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในบุรีรัมย์ Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU GPU RAM SSD แบตเตอรี่ จอ สภาพและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คบุรีรัมย์ เช็กรุ่น สเปก แบตเตอรี่และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 1 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-เลย/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คเลย Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในจังหวัดเลย Notebook Laptop และ Gaming Notebook ส่งรุ่น สเปก รูป แบตเตอรี่ อาการและอุปกรณ์เพื่อเช็กราคาเบื้องต้นก่อนตัดสินใจขาย',
    h1: 'รับซื้อโน๊ตบุ๊คเลย เช็กราคาจากรุ่น สเปก และสภาพก่อนเดินทาง',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 1 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโทรศัพท์มือถือ-จ/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อโทรศัพท์มือถือมือสอง ภาคอีสาน เช็กราคาสมาร์ทโฟนก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโทรศัพท์มือถือมือสองสำหรับผู้ขายในภาคอีสาน ทั้ง iPhone และสมาร์ทโฟนหลายรุ่น ประเมินจากรุ่น ความจุ แบตเตอรี่ หน้าจอ สภาพ อุปกรณ์และประวัติซ่อม ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโทรศัพท์มือถือมือสองในภาคอีสาน เช็กรุ่น สภาพ และราคาก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 2 historical regional winner - released to INDEX'
  },
  {
    path: '/รับซื้อมือถือ-อุบล/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อมือถืออุบลราชธานี iPhone Android เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อมือถือมือสองในอุบลราชธานี ทั้ง iPhone และ Android ประเมินจากรุ่น ความจุ แบตเตอรี่ หน้าจอ สภาพ อุปกรณ์และประวัติซ่อม ส่งรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อมือถืออุบลราชธานี เช็กรุ่น แบตเตอรี่ และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-ชัยภูมิ/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คชัยภูมิ Notebook Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในชัยภูมิ Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU GPU RAM SSD แบตเตอรี่ จอ สภาพและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คชัยภูมิ เช็กสเปก แบตเตอรี่ และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อไอโฟน-มหาสารคาม/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อไอโฟนมหาสารคาม iPhone มือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ iPhone มือสองในมหาสารคาม ประเมินจากรุ่น ความจุ Battery Health หน้าจอ Face ID กล้อง สภาพ อุปกรณ์และประวัติซ่อม ส่งรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อไอโฟนมหาสารคาม เช็กรุ่น Battery Health และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-สกลนคร/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คสกลนคร Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในสกลนคร Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU GPU RAM SSD Battery จอ สภาพและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คสกลนคร เช็กรุ่น สเปก และสภาพก่อนตัดสินใจขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-นครพนม/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คนครพนม Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในนครพนม Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU RAM SSD GPU แบตเตอรี่ จอ สภาพและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คนครพนม เช็กรุ่น สเปก และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 3 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-นครราชส/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คโคราช นครราชสีมา Gaming Notebook เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในโคราช นครราชสีมา ทั้ง Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU GPU RAM SSD แบตเตอรี่ จอ สภาพและอุปกรณ์ก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คโคราช นครราชสีมา เช็กสเปกและสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 3 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อเมืองขอนแก่น/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'macbook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อแมคบุ๊ค/',
    title: 'รับซื้อ MacBook ขอนแก่น MacBook Air Pro เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ MacBook มือสองในขอนแก่น ทั้ง MacBook Air และ MacBook Pro ประเมินจากรุ่น ชิป RAM Storage Battery Cycle หน้าจอ สภาพ อุปกรณ์และประวัติซ่อม',
    h1: 'รับซื้อ MacBook ขอนแก่น เช็กรุ่น ชิป Battery และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 3 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-notebook-ยโสธร/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คยโสธร Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในยโสธร Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU RAM SSD GPU แบตเตอรี่ จอ สภาพและประวัติซ่อม เช็กราคาก่อนตัดสินใจ',
    h1: 'รับซื้อโน๊ตบุ๊คยโสธร เช็กสภาพและความคุ้มค่าก่อนซ่อมหรือขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 3 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-ขอนแก่น/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คขอนแก่น Notebook Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในขอนแก่น Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU GPU RAM SSD Battery จอ สภาพและอุปกรณ์ ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อโน๊ตบุ๊คขอนแก่น เช็กรุ่น สเปก และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 3 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อ-notebook-อำเภอพล-ขอนแก่น/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค-ขอนแก่น/',
    title: 'รับซื้อโน๊ตบุ๊คอำเภอพล ขอนแก่น Notebook มือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในอำเภอพล ขอนแก่น ส่งรุ่น CPU RAM SSD GPU แบตเตอรี่ รูป สภาพและอุปกรณ์เพื่อเช็กราคาเบื้องต้นก่อนตัดสินใจขาย',
    h1: 'รับซื้อโน๊ตบุ๊คอำเภอพล ขอนแก่น เช็กรุ่นและสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 4 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโทรศัพท์-มือถือ-ย/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อมือถือยโสธร โทรศัพท์มือสอง iPhone Android เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อมือถือมือสองในยโสธร ทั้ง iPhone และ Android ประเมินจากรุ่น ความจุ Battery หน้าจอ กล้อง สภาพ อุปกรณ์และประวัติซ่อม ส่งรูปเช็กราคาก่อนขาย',
    h1: 'รับซื้อมือถือยโสธร เช็กรุ่น แบตเตอรี่ หน้าจอ และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 4 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-กาฬสินธ/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คกาฬสินธุ์ Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในกาฬสินธุ์ Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU RAM SSD GPU Battery หน้าจอ สภาพและอุปกรณ์ก่อนตัดสินใจขาย',
    h1: 'รับซื้อโน๊ตบุ๊คกาฬสินธุ์ เช็กสเปก Battery และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 4 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อ-notebook-ชุมแพ-ขอนแก่น/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค-ขอนแก่น/',
    title: 'รับซื้อโน๊ตบุ๊คชุมแพ ขอนแก่น Notebook Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในชุมแพ ขอนแก่น Notebook Laptop และ Gaming Notebook ส่งรุ่น สเปก Battery รูป อาการและอุปกรณ์เพื่อเช็กราคาก่อนตัดสินใจขาย',
    h1: 'รับซื้อโน๊ตบุ๊คชุมแพ ขอนแก่น เช็กสเปกและอาการก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 4 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-ร้อยเอ็/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คร้อยเอ็ด Notebook Laptop เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในร้อยเอ็ด Notebook Laptop และ Gaming Notebook ประเมินจากรุ่น CPU RAM SSD GPU Battery หน้าจอ สภาพ อุปกรณ์และประวัติซ่อม',
    h1: 'รับซื้อโน๊ตบุ๊คร้อยเอ็ด เช็กสภาพ อุปกรณ์ และราคาก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 4 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-หนองบัว/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คหนองบัวลำภู Notebook มือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในหนองบัวลำภู Notebook Laptop และ Gaming Notebook เช็กรุ่น CPU RAM SSD GPU Battery สภาพและอุปกรณ์ก่อนตัดสินใจขาย',
    h1: 'รับซื้อโน๊ตบุ๊คหนองบัวลำภู ส่งสเปกและรูปเช็กราคาก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 5 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อโน๊ตบุ๊ค-อุดรธาน/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'notebook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อโน๊ตบุ๊ค/',
    title: 'รับซื้อโน๊ตบุ๊คอุดรธานี Notebook บริษัท Gaming เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อโน๊ตบุ๊คมือสองในอุดรธานี ทั้ง Notebook สำนักงาน Business Laptop และ Gaming Notebook ประเมินจากรุ่น สเปก Battery สภาพ อุปกรณ์และจำนวนเครื่อง',
    h1: 'รับซื้อโน๊ตบุ๊คอุดรธานี เช็กสเปก เครื่องเดี่ยวหรือหลายเครื่องก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 5 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อลำโพง-ร้อยเอ็ด-jbl-marshall/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'audio',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อลำโพง/',
    title: 'รับซื้อลำโพงร้อยเอ็ด JBL Marshall Bluetooth มือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อลำโพงมือสองในร้อยเอ็ด รวมลำโพง Bluetooth และรุ่นพกพาหลายแบรนด์ ประเมินจากรุ่น Battery เสียง การเชื่อมต่อ สภาพ อุปกรณ์และประวัติซ่อม',
    h1: 'รับซื้อลำโพงร้อยเอ็ด เช็กรุ่น Battery เสียง และการเชื่อมต่อก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 5 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อไอโฟน-iphone-ร้อยเอ็ด/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อไอโฟนร้อยเอ็ด iPhone มือสอง เช็ก Battery และสภาพก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ iPhone มือสองในร้อยเอ็ด ประเมินจากรุ่น ความจุ Battery Health หน้าจอ Face ID กล้อง สภาพ อุปกรณ์และประวัติซ่อม ส่งข้อมูลเช็กราคาก่อนขาย',
    h1: 'รับซื้อไอโฟนร้อยเอ็ด เช็กรุ่น Battery Health และประวัติเครื่องก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 5 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อกล้องมือสองมุก/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้องมือสองมุกดาหาร DSLR Mirrorless เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสองในมุกดาหาร ทั้ง DSLR Mirrorless กล้องพร้อมเลนส์และอุปกรณ์ ประเมินจากรุ่น Sensor Shutter จอ ช่องมองภาพ เลนส์ สภาพและประวัติซ่อม',
    h1: 'รับซื้อกล้องมือสองมุกดาหาร เช็ก Body เลนส์ Sensor และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 5 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อคอม-สารคาม/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'pc',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อคอม/',
    title: 'รับซื้อคอมมหาสารคาม คอมประกอบ Gaming PC เช็กสเปกก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อคอมมือสองในมหาสารคาม ทั้งคอมประกอบ Gaming PC คอมสำนักงานและเครื่องใช้งานทั่วไป ประเมินจาก CPU GPU RAM SSD Mainboard PSU สภาพและอุปกรณ์',
    h1: 'รับซื้อคอมมหาสารคาม เช็ก CPU การ์ดจอ และสเปกก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 6 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อmacbook-อุดรธานี/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'macbook',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อแมคบุ๊ค/',
    title: 'รับซื้อ MacBook อุดรธานี Air Pro เช็ก Battery Cycle ก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ MacBook มือสองในอุดรธานี ทั้ง MacBook Air และ MacBook Pro ประเมินจากรุ่น ชิป RAM Storage Battery Cycle จอ Keyboard Port อุปกรณ์และประวัติซ่อม',
    h1: 'รับซื้อ MacBook อุดรธานี เช็กรุ่น ชิป Battery Cycle และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 6 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อกล้องอุบล-กล้องcanon-niko/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้องอุบล DSLR Mirrorless Canon Nikon เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสองในอุบลราชธานี ทั้ง DSLR Mirrorless และชุดกล้องพร้อมเลนส์ ประเมินจากรุ่น Mount Sensor Shutter AF จอ EVF เลนส์ สภาพและอุปกรณ์',
    h1: 'รับซื้อกล้องอุบล เช็กรุ่น Body Lens Shutter และระบบโฟกัสก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 6 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อกล้อง-ยโสธร/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้องยโสธร กล้องมือสอง มีอาการก็เช็กราคาได้ | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสองในยโสธร ทั้ง DSLR Mirrorless Body และ Lens เช็กสภาพ Sensor จอ EVF Shutter Focus รา ฝุ่น อาการเสียและต้นทุนก่อนซ่อมหรือขาย',
    h1: 'รับซื้อกล้องยโสธร เช็กสภาพและความคุ้มค่าก่อนซ่อมหรือขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 6 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อกล้องถ่ายรูป-ศรี/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้องศรีสะเกษ Body Lens อุปกรณ์หลายชิ้น เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสองในศรีสะเกษ ทั้ง Body Lens DSLR Mirrorless และอุปกรณ์กล้อง ประเมินแยกรุ่น เลนส์ Shutter Battery Charger Flash และสภาพก่อนขาย',
    h1: 'รับซื้อกล้องศรีสะเกษ ประเมิน Body Lens และอุปกรณ์แยกก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'E2 Batch 6 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อกล้องมือสองสุร/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้องมือสองสุรินทร์ DSLR Mirrorless Lens เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อกล้องมือสองในสุรินทร์ ทั้ง DSLR Mirrorless Body และ Lens ประเมินจากรุ่น ระบบกล้อง Sensor Shutter Focus เลนส์ Battery อุปกรณ์และสภาพก่อนขาย',
    h1: 'รับซื้อกล้องมือสองสุรินทร์ เช็กระบบ Body Lens และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'Final E2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อลำโพง-ยโสธร/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'audio',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อลำโพง/',
    title: 'รับซื้อลำโพงยโสธร Bluetooth JBL Marshall มือสอง เช็กราคาก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อลำโพงมือสองในยโสธร ทั้ง Bluetooth และ Portable Speaker ประเมินจากรุ่น Battery เสียง Driver Passive Radiator การเชื่อมต่อ Port สภาพและอุปกรณ์',
    h1: 'รับซื้อลำโพงยโสธร เช็ก Battery เสียง Driver และสภาพก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'Final E2 historical local winner - released to INDEX'
  },
  {
    path: '/รับซื้อไอแพด-ยโสธร-ipad/',
    state: 'INDEX',
    pageType: 'location',
    contentCluster: 'ipad',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอแพด/',
    title: 'รับซื้อ iPad ยโสธร Pro Air mini มือสอง เช็ก Battery และสภาพก่อนขาย | เรารับซื้อ.com',
    description: 'รับซื้อ iPad มือสองในยโสธร ทั้ง iPad Pro Air mini และรุ่นมาตรฐาน ประเมินจากรุ่น ชิป ความจุ Wi-Fi Cellular Battery จอ Touch อุปกรณ์และประวัติซ่อม',
    h1: 'รับซื้อ iPad ยโสธร เช็กรุ่น ความจุ Battery จอ และอุปกรณ์ก่อนขาย',
    gscPriority: 'high',
    migrationStatus: 'rebuilt',
    contentStatus: 'READY',
    notes: 'Final E2 historical local winner - released to INDEX'
  }
];

/**
 * 2. Core Navigation Hubs & Structural Pages (HOLD_NOINDEX pending owner review)
 */
export const CORE_HOLD_NOINDEX_PAGES: SeoManifestRecord[] = [
  {
    path: '/รับซื้อคอมประกอบ/',
    state: 'HOLD_NOINDEX',
    pageType: 'category',
    contentCluster: 'pc',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อคอม/',
    title: 'รับซื้อคอมประกอบ มือสอง Gaming PC สเปกแรง | เรารับซื้อ.com',
    description: 'รับซื้อคอมประกอบ Gaming PC เวิร์กสเตชัน ตีราคาแยกชิ้นส่วนตามอุปกรณ์จริง CPU, GPU, RAM, Mainboard, SSD',
    h1: 'รับซื้อคอมประกอบและชิ้นส่วนคอมพิวเตอร์',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/รับซื้อเครื่องเกม/',
    state: 'HOLD_NOINDEX',
    pageType: 'category',
    contentCluster: 'gaming',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อเครื่องเกม PS5, PS4, Nintendo Switch, Steam Deck | เรารับซื้อ.com',
    description: 'รับซื้อคอนโซลและเครื่องเล่นเกมพกพา PlayStation, Nintendo Switch, Xbox, Handheld PC อุปกรณ์เสริม จอย แผ่นเกม',
    h1: 'รับซื้อเครื่องเล่นเกมคอนโซลและพกพา',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/รับซื้อ-apple-watch/',
    state: 'HOLD_NOINDEX',
    pageType: 'category',
    contentCluster: 'iphone',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อ Apple Watch Series, Ultra, SE มือสอง | เรารับซื้อ.com',
    description: 'รับซื้อ Apple Watch ทุกตระกูล Ultra, Series, SE ตรวจสอบสภาพบอดี้ หน้าจอ และสุขภาพแบตเตอรี่ ให้ราคายุติธรรม',
    h1: 'รับซื้อ Apple Watch มือสอง',
    gscPriority: 'medium',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/รับซื้อ-ups/',
    state: 'HOLD_NOINDEX',
    pageType: 'category',
    contentCluster: 'b2b',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อเครื่องสำรองไฟ UPS มือสอง ทุกขนาด | เรารับซื้อ.com',
    description: 'รับซื้อเครื่องสำรองไฟ UPS APC, Eaton, Cleanline, Syndome ทั้งขนาดบ้าน สำนักงาน และตู้แร็คระบบใหญ่',
    h1: 'รับซื้อเครื่องสำรองไฟ UPS มือสอง',
    gscPriority: 'medium',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/รับซื้อสมาร์ทโฟน-android/',
    state: 'HOLD_NOINDEX',
    pageType: 'category',
    contentCluster: 'android',
    primaryIntent: 'buyback',
    canonical: 'self',
    parent: '/รับซื้อ/',
    title: 'รับซื้อสมาร์ทโฟน Android Samsung, Xiaomi, OPPO, Vivo | เรารับซื้อ.com',
    description: 'รับซื้อโทรศัพท์มือถือระบบ Android รุ่นเรือธงและรุ่นยอดนิยม Samsung Galaxy, Xiaomi, OPPO, Vivo เช็กสเปก ตีราคาตรงตามสภาพ',
    h1: 'รับซื้อสมาร์ทโฟน Android มือสอง',
    gscPriority: 'medium',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/เช็กราคาก่อนขาย/',
    state: 'HOLD_NOINDEX',
    pageType: 'guide',
    contentCluster: 'general',
    primaryIntent: 'price_check',
    canonical: 'self',
    title: 'เช็กราคาก่อนขาย วิธีประเมินมูลค่าสินค้าไอทีมือสอง | เรารับซื้อ.com',
    description: 'แนวทางการประเมินราคาก่อนขายสินค้าไอที ปัจจัยที่มีผลต่อราคา สภาพเครื่อง อุปกรณ์ครบกล่อง และประกันคงเหลือ เพื่อให้ได้ราคาดีที่สุด',
    h1: 'เช็กราคาก่อนขาย เข้าใจปัจจัยประเมินสภาพ',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/ราคากลางรับซื้อ/',
    state: 'HOLD_NOINDEX',
    pageType: 'guide',
    contentCluster: 'general',
    primaryIntent: 'price_check',
    canonical: 'self',
    title: 'ราคากลางรับซื้อสินค้าไอทีมือสอง อัปเดตล่าสุด | เรารับซื้อ.com',
    description: 'มาตรฐานราคากลางรับซื้อสินค้าไอที โน๊ตบุ๊ค คอมพิวเตอร์ มือถือ แท็บเล็ต ให้คุณใช้เป็นแนวทางเปรียบเทียบก่อนตัดสินใจขาย',
    h1: 'แนวทางราคากลางรับซื้อสินค้าไอที',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/เกี่ยวกับเรา/',
    state: 'HOLD_NOINDEX',
    pageType: 'static',
    contentCluster: 'general',
    primaryIntent: 'trust',
    canonical: 'self',
    title: 'เกี่ยวกับเรา ข้อมูลบริการและพันธกิจ | เรารับซื้อ.com',
    description: 'ทำความรู้จัก เรารับซื้อ.com บริการรับซื้อสินค้าไอทีที่เน้นความโปร่งใส ปลอดภัย ซื่อตรง และให้คำปรึกษาก่อนตัดสินใจขาย',
    h1: 'เกี่ยวกับ เรารับซื้อ.com',
    gscPriority: 'medium',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/ความน่าเชื่อถือ/',
    state: 'HOLD_NOINDEX',
    pageType: 'static',
    contentCluster: 'general',
    primaryIntent: 'trust',
    canonical: 'self',
    title: 'ความน่าเชื่อถือ มาตรฐานการประเมินและการซื้อขาย | เรารับซื้อ.com',
    description: 'มาตรฐานความปลอดภัย กระบวนการล้างข้อมูลส่วนบุคคล (Data Privacy) และหลักฐานการทำธุรกรรมที่โปร่งใส',
    h1: 'มาตรฐานความปลอดภัยและความน่าเชื่อถือ',
    gscPriority: 'high',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/contact/',
    state: 'HOLD_NOINDEX',
    pageType: 'static',
    contentCluster: 'general',
    primaryIntent: 'contact',
    canonical: 'self',
    title: 'ติดต่อเรา ช่องทางส่งรูปประเมินราคา | เรารับซื้อ.com',
    description: 'ติดต่อทีมงาน เรารับซื้อ.com เพื่อส่งรูปถ่าย สเปก และรายละเอียดสินค้าเพื่อประเมินราคาเบื้องต้นได้ฟรีผ่าน LINE @webuy',
    h1: 'ติดต่อส่งรูปประเมินราคาเบื้องต้น',
    gscPriority: 'critical',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/terms/',
    state: 'HOLD_NOINDEX',
    pageType: 'policy',
    contentCluster: 'general',
    primaryIntent: 'policy',
    canonical: 'self',
    title: 'ข้อกำหนดและเงื่อนไขการใช้บริการ | เรารับซื้อ.com',
    description: 'ข้อกำหนด เงื่อนไขการรับซื้อสินค้าไอที และหลักเกณฑ์การตรวจสอบกรรมสิทธิ์สินค้า',
    h1: 'ข้อกำหนดและเงื่อนไขการใช้บริการ',
    gscPriority: 'low',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/privacy-policy/',
    state: 'HOLD_NOINDEX',
    pageType: 'policy',
    contentCluster: 'general',
    primaryIntent: 'policy',
    canonical: 'self',
    title: 'นโยบายความเป็นส่วนตัว (Privacy Policy) | เรารับซื้อ.com',
    description: 'นโยบายการคุ้มครองข้อมูลส่วนบุคคลและมาตรฐานการล้างข้อมูลอุปกรณ์ก่อนการส่งต่อ',
    h1: 'นโยบายความเป็นส่วนตัว',
    gscPriority: 'low',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  },
  {
    path: '/cookie-policy/',
    state: 'HOLD_NOINDEX',
    pageType: 'policy',
    contentCluster: 'general',
    primaryIntent: 'policy',
    canonical: 'self',
    title: 'นโยบายคุกกี้ (Cookie Policy) | เรารับซื้อ.com',
    description: 'ข้อมูลเกี่ยวกับการใช้งานคุกกี้เพื่อปรับปรุงประสบการณ์การใช้งานบนเว็บไซต์',
    h1: 'นโยบายคุกกี้',
    gscPriority: 'low',
    migrationStatus: 'preserved',
    contentStatus: 'PENDING_REVIEW'
  }
];

/**
 * 3. Authoritative 11 REBUILD_INDEX Candidates (CONTENT_REQUIRED / HOLD_NOINDEX)
 */
export const REBUILD_INDEX_CANDIDATES: SeoManifestRecord[] = [
  {
    path: '/รับซื้อไอโฟน-ขอนแก่น/',
    state: 'HOLD_NOINDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อไอโฟน ขอนแก่น | เรารับซื้อ.com',
    contentStatus: 'CONTENT_REQUIRED',
    migrationStatus: 'hold',
    notes: 'REBUILD_INDEX survivor candidate - awaiting unique local iPhone content.'
  },
  {
    path: '/รับซื้อไอโฟน-จังหวัดอุด/',
    state: 'HOLD_NOINDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อไอโฟน อุดรธานี | เรารับซื้อ.com',
    contentStatus: 'CONTENT_REQUIRED',
    migrationStatus: 'hold',
    notes: 'REBUILD_INDEX survivor candidate - awaiting unique local iPhone content.'
  },
  {
    path: '/รับซื้อไอโฟน-ยโสธร/',
    state: 'HOLD_NOINDEX',
    pageType: 'location',
    contentCluster: 'iphone',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อไอโฟน/',
    title: 'รับซื้อไอโฟน ยโสธร | เรารับซื้อ.com',
    contentStatus: 'CONTENT_REQUIRED',
    migrationStatus: 'hold',
    notes: 'REBUILD_INDEX survivor candidate - awaiting unique local iPhone content.'
  },
  {
    path: '/buy-camera-mahasarakam/',
    state: 'HOLD_NOINDEX',
    pageType: 'location',
    contentCluster: 'camera',
    primaryIntent: 'local',
    canonical: 'self',
    parent: '/รับซื้อกล้อง/',
    title: 'รับซื้อกล้อง มหาสารคาม | เรารับซื้อ.com',
    contentStatus: 'CONTENT_REQUIRED',
    migrationStatus: 'hold',
    notes: 'REBUILD_INDEX survivor candidate - awaiting unique local camera content.'
  }
];

/**
 * 4. Authoritative 29 HOLD_NOINDEX Historical Survivor Pages
 */
export const HOLD_NOINDEX_SURVIVORS: SeoManifestRecord[] = [
  '/ขายโน๊ตบุ๊ค-ขอนแก่น/',
  '/ร้านรับซื้อโน๊ตบุ๊คอุบ-2/',
  '/รับซื้อกล้อง-canon-2/',
  '/รับซื้อกล้อง-sony-a6400/',
  '/รับซื้อกล้อง-sony-rx100/',
  '/รับซื้อกล้อง-sony-a7/',
  '/รับซื้อกล้องมือสองอุบล/',
  '/รับซื้อกล้องมือสองขอนแ/',
  '/รับซื้อกล้องมือสองอุดร/',
  '/รับซื้อกล้องมือสองนครร/',
  '/รับซื้อกล้องมือสองบุรี/',
  '/รับซื้อกล้องมือสองศรี/',
  '/รับซื้อกล้องมือสองกาฬ/',
  '/รับซื้อกล้องมือสองมหา/',
  '/รับซื้อกล้องมือสองยโสธ/',
  '/รับซื้อกล้องมือสองมุกด/',
  '/รับซื้อกล้องมือสองบึง/',
  '/รับซื้อกล้องมือสองหนอ/',
  '/รับซื้อกล้องนครราชสีมา/',
  '/รับซื้อกล้องเลนส์/',
  '/ร้านรับซื้อโน๊ตบุ๊คในอ/',
  '/รับซื้อกล้อง-รับซื้อเลน/',
  '/buy-camera-ubon/',
  '/buy-camera-nongkai/',
  '/รับซื้อไอโฟน-15-iphone-15/',
  '/รับซื้อไอโฟน-iphone-อุบล/',
  '/รับซื้อกล้อง-canon/',
  '/รับซื้อกล้อง-nikon-รับซื้อกล/',
  '/รับซื้อกล้อง-ใกล้ฉัน/'
].map(p => ({
  path: p,
  state: 'HOLD_NOINDEX',
  contentStatus: 'PENDING_REVIEW',
  migrationStatus: 'hold',
  notes: 'Historical survivor in hold/review'
}));

/**
 * 5. Unexpected Legacy Paths Requiring Review (REVIEW_REQUIRED / DRAFT)
 */
export const UNREVIEWED_LEGACY_PATHS: SeoManifestRecord[] = [
  "/100-อันดับ-กล้อง-fujifilm-ในตลาดมือ/",
  "/10-อันดับ-กล้อง-fujifilm-ในตลาดมือ/",
  "/1090/",
  "/1199/",
  "/1209/",
  "/1216/",
  "/1230/",
  "/1340/",
  "/1352/",
  "/1362/",
  "/1477/",
  "/1480/",
  "/1482/",
  "/1494/",
  "/1498/",
  "/1500/",
  "/1502/",
  "/1504/",
  "/1508/",
  "/1511/",
  "/1515/",
  "/1517/"
].map(p => ({
  path: p,
  state: 'DRAFT',
  contentStatus: 'NOT_APPLICABLE',
  migrationStatus: 'hold',
  notes: 'Unapproved legacy numeric ID / ranking path requiring owner review (REVIEW_REQUIRED).'
}));

/**
 * 6. Master Manifest Map Assembly
 */
const ALL_MANIFEST_RECORDS: SeoManifestRecord[] = [
  ...APPROVED_INDEX_PAGES,
  ...CORE_HOLD_NOINDEX_PAGES,
  ...REBUILD_INDEX_CANDIDATES,
  ...HOLD_NOINDEX_SURVIVORS,
  ...UNREVIEWED_LEGACY_PATHS,
  ...PLANNED_PAGES
];

export const SEO_MANIFEST_MAP = new Map<string, SeoManifestRecord>();

for (const rec of ALL_MANIFEST_RECORDS) {
  const norm = normalizePath(rec.path);
  SEO_MANIFEST_MAP.set(norm, { ...rec, path: norm });
}

// Register 301 Redirects
for (const rule of RAW_REDIRECT_RULES) {
  const src = normalizePath(rule.source);
  const tgt = normalizePath(rule.target);
  if (!SEO_MANIFEST_MAP.has(src)) {
    SEO_MANIFEST_MAP.set(src, {
      path: src,
      state: 'REDIRECT',
      redirectTo: tgt,
      migrationStatus: 'redirected',
      contentStatus: 'NOT_APPLICABLE',
      notes: rule.reason
    });
  }
}

// Register 410 GONE Paths (Authoritative 206)
for (const g of GONE_PATHS_RAW) {
  const norm = normalizePath(g);
  if (!SEO_MANIFEST_MAP.has(norm)) {
    SEO_MANIFEST_MAP.set(norm, {
      path: norm,
      state: 'GONE',
      migrationStatus: 'gone',
      contentStatus: 'NOT_APPLICABLE',
      notes: 'Quarantined off-topic / spam legacy URL.'
    });
  }
}

export function getManifestRecord(path: string): SeoManifestRecord | undefined {
  return SEO_MANIFEST_MAP.get(normalizePath(path));
}
